{% set name = "jupyterlab-code-snippets" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 465f31b51f2458881e6ece61ca1681d4d5855c3eba65e7e6e19baf5840303ae9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - nodejs >=12.0.0
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.4.0
    - jupyterlab >=3.4.7,<4.0.0
    - pip
    - python >=3.7
    - wheel
  run:
    - jupyterlab >=3,<4
    - python >=3.6

test:
  commands:
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab-code-snippets.*OK"

about:
  home: https://github.com/jupytercalpoly/jupyterlab-code-snippets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Save, reuse, and share code snippets using JupyterLab Code Snippets'
  dev_url: https://github.com/jupytercalpoly/jupyterlab-code-snippets

extra:
  recipe-maintainers:
    - m-rossi
